In [32]:
import pickle 
import numpy as np
import pandas as pd
import statistics
from PIL import Image
import os 
import random
import time
import matplotlib.pyplot as plt
import netaddr

In [33]:
#pip install netaddr

In [34]:
cwd = os.getcwd()

In [35]:
cwd

'C:\\Users\\jghadermazi\\Box\\GNN Project\\Code files'

In [ ]:
#directory should change based on the device, for laptop it should be users//jalal for office desktop it is users//jghadermazi

In [8]:
wed_data = pd.read_pickle(r'C:\\Users\\jghadermazi\\Box\\GAN Project\\Sample data\\Friday_Packet_Level_Data.pkl')

In [48]:
df1 = wed_data.copy()

In [49]:
df1[['Payload']] = df1[['Payload']].replace('', '00')

In [50]:
df1

,Epoch Time,Source IP,Dst IP,Source Port,Dst Port,Stream Index,Sequence Number,Eth Header,IP Header,TCP Header,Payload,Direction,Binary Label,Class Label
0,1499432653.990571000,192.168.10.9,205.174.165.73,1841,8080,13099,0,00c1b114eb31b8ac6f1d1f6c0800,450000346c8f40008006508bc0a80a09cdaea549,07311f905c691851000000008002200075eb0000020405...,00,fwd,1.0,12.0
1,1499432653.991397000,205.174.165.73,192.168.10.9,8080,1841,13099,0,b8ac6f1d1f6c00c1b114eb310800,45000034000040003e06ff1acdaea549c0a80a09,1f90073113dd44cb5c69185280127210cb220000020405...,00,bwd,1.0,12.0
2,1499432653.991520000,192.168.10.9,205.174.165.73,1841,8080,13099,1,00c1b114eb31b8ac6f1d1f6c0800,450000286c90400080065096c0a80a09cdaea549,07311f905c69185213dd44cc501001007d050000,000000000000,fwd,1.0,12.0
3,1499432653.992542000,192.168.10.9,205.174.165.73,1841,8080,13099,1,00c1b114eb31b8ac6f1d1f6c0800,450000ea6c91400080064fd3c0a80a09cdaea549,07311f905c69185213dd44cc50180100307c0000,474554202f6170692f706f703f626f7469643d6d697461...,fwd,1.0,12.0
4,1499432653.993057000,205.174.165.73,192.168.10.9,8080,1841,13099,1,b8ac6f1d1f6c00c1b114eb310800,45000028822a40003e067cfccdaea549c0a80a09,1f90073113dd44cc5c691914501000ed7c560000,000000000000,bwd,1.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260217,1499454300.212460000,172.217.12.205,192.168.10.14,443,58093,280715,3982,b8ac6f3607ee00c1b114eb310800,450000f7dfe60000340621beacd90ccdc0a80a0e,01bbe2eda84cbf47d787ec2350180169decb0000,17030300ca0000000000000003b9423a0b5901a1d34005...,bwd,0.0,0.0
5260218,1499454300.212688000,172.217.12.205,192.168.10.14,443,58093,280715,4189,b8ac6f3607ee00c1b114eb310800,4500019ddfe7000034062117acd90ccdc0a80a0e,01bbe2eda84cc016d787ec2350180169e0870000,1703030170000000000000000427cfa8c91d47cda4d459...,bwd,0.0,0.0
5260219,1499454300.212736000,172.217.12.205,192.168.10.14,443,58093,280715,4562,b8ac6f3607ee00c1b114eb310800,450000acdfe8000034062207acd90ccdc0a80a0e,01bbe2eda84cc18bd787ec235018016903ef0000,170303007f000000000000000529465b5b09e2c6a7bf19...,bwd,0.0,0.0
5260220,1499454300.212738000,172.217.12.205,192.168.10.14,443,58093,280715,4694,b8ac6f3607ee00c1b114eb310800,45000056dfe900003406225cacd90ccdc0a80a0e,01bbe2eda84cc20fd787ec2350180169e55a0000,170303002900000000000000066521f26029ac678a3244...,bwd,0.0,0.0
5260221,1499454300.214231000,93.184.216.172,192.168.10.14,443,58096,280754,5501,b8ac6f3607ee00c1b114eb310800,4500012a1b104000370626a35db8d8acc0a80a0e,01bbe2f014324df0b28987bb501801203b4a0000,16030300ca040000c60000012c00c0a905c333f9859839...,bwd,0.0,0.0

In [51]:
#benign    0
#dos slowloris    1
#dos slowhttptest   2
#dos hulk     3
#dos goldeneye    4
#heartbleed    5
#ftp patator    6
#ssh patator    7
#webattack bruteforce    8
#webattack xss     9
#webattack sql injection 10
#infiltration     11
#botnet     12
#portscan   13
#ddos     14

In [52]:
df1['Class Label'].value_counts()

0.0     3661387
14.0    1265657
13.0     323307
12.0       9871
Name: Class Label, dtype: int64

In [53]:
df = df1[df1['Class Label']== 0]

In [54]:
df = df.reset_index(inplace = False)

87847

In [57]:
df

,index,Epoch Time,Source IP,Dst IP,Source Port,Dst Port,Stream Index,Sequence Number,Eth Header,IP Header,TCP Header,Payload,Direction,Binary Label,Class Label
0,1598835,1499428790.315195000,192.168.10.50,192.168.10.3,56108,3268,0,1,1866da9be37d0019b90a69f10800,450001c7c50040004006deaac0a80a32c0a80a03,db2c0cc46a70fd5c3630dfa980180179d0aa0000010108...,0000018f6082018b06092a864886f71201020202011100...,fwd,0.0,0.0
1,1598836,1499428790.315200000,192.168.10.50,192.168.10.3,56108,3268,0,1,1866da9be37d0019b90a69f10800,450001c7c50040004006deaac0a80a32c0a80a03,db2c0cc46a70fd5c3630dfa980180179d0aa0000010108...,0000018f6082018b06092a864886f71201020202011100...,fwd,0.0,0.0
2,1598837,1499428790.315541000,192.168.10.50,192.168.10.3,56108,3268,0,404,1866da9be37d0019b90a69f10800,45000034c50140004006e03cc0a80a32c0a80a03,db2c0cc46a70feef3630dff180100179db7d0000010108...,00,fwd,0.0,0.0
3,1598838,1499428790.315545000,192.168.10.50,192.168.10.3,56108,3268,0,404,1866da9be37d0019b90a69f10800,45000034c50140004006e03cc0a80a32c0a80a03,db2c0cc46a70feef3630dff180100179db7d0000010108...,00,fwd,0.0,0.0
4,1598839,1499428790.316273000,192.168.10.50,192.168.10.3,42144,389,1,1,1866da9be37d0019b90a69f10800,450001c7d16740004006d243c0a80a32c0a80a03,a4a0018554175800ff37c390801803bbfee40000010108...,0000018f6082018b06092a864886f71201020202011100...,fwd,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661382,5260217,1499454300.212460000,172.217.12.205,192.168.10.14,443,58093,280715,3982,b8ac6f3607ee00c1b114eb310800,450000f7dfe60000340621beacd90ccdc0a80a0e,01bbe2eda84cbf47d787ec2350180169decb0000,17030300ca0000000000000003b9423a0b5901a1d34005...,bwd,0.0,0.0
3661383,5260218,1499454300.212688000,172.217.12.205,192.168.10.14,443,58093,280715,4189,b8ac6f3607ee00c1b114eb310800,4500019ddfe7000034062117acd90ccdc0a80a0e,01bbe2eda84cc016d787ec2350180169e0870000,1703030170000000000000000427cfa8c91d47cda4d459...,bwd,0.0,0.0
3661384,5260219,1499454300.212736000,172.217.12.205,192.168.10.14,443,58093,280715,4562,b8ac6f3607ee00c1b114eb310800,450000acdfe8000034062207acd90ccdc0a80a0e,01bbe2eda84cc18bd787ec235018016903ef0000,170303007f000000000000000529465b5b09e2c6a7bf19...,bwd,0.0,0.0
3661385,5260220,1499454300.212738000,172.217.12.205,192.168.10.14,443,58093,280715,4694,b8ac6f3607ee00c1b114eb310800,45000056dfe900003406225cacd90ccdc0a80a0e,01bbe2eda84cc20fd787ec2350180169e55a0000,170303002900000000000000066521f26029ac678a3244...,bwd,0.0,0.0
3661386,5260221,1499454300.214231000,93.184.216.172,192.168.10.14,443,58096,280754,5501,b8ac6f3607ee00c1b114eb310800,4500012a1b104000370626a35db8d8acc0a80a0e,01bbe2f014324df0b28987bb501801203b4a0000,16030300ca040000c60000012c00c0a905c333f9859839...,bwd,0.0,0.0

In [58]:
ip_header_lst = []

for i in range(len(df)):
    x = df['IP Header'][i]
    byte_array = bytes.fromhex(x)
    byte_lst = list(byte_array)
    if (len(byte_lst) < 20):
            output = np.pad(byte_lst, (0, 20-len(byte_lst)), 'constant')
    else:
            output = np.array(byte_lst[0:20].copy())
            
    output = np.delete(output, [0, 1, 9, 12, 13, 14, 15, 16, 17, 18, 19])
    
    output = np.abs(output.astype(float))/255
    ip_header_lst.append(output)
    
df['IP Header Array'] = ip_header_lst

In [59]:
tcp_header_lst = []

for i in range(len(df)):
    x = df['TCP Header'][i]
    byte_array = bytes.fromhex(x)
    byte_lst = list(byte_array)
    if (len(byte_lst) < 20):
            output = np.pad(byte_lst, (0, 20-len(byte_lst)), 'constant')
    else:
            output = np.array(byte_lst[0:20].copy())
            
    output = np.delete(output, [0, 1, 2, 3])
    output = np.abs(output.astype(float))/255
    
    tcp_header_lst.append(output)
    
df['TCP Header Array'] = tcp_header_lst

In [60]:
df['pkt_header_values'] = df.apply(lambda x : (np.append(x['IP Header Array'], x['TCP Header Array'])), axis=1)

In [61]:
new_cols = ['Source IP', 'Dst IP', 'Source Port', 'Dst Port','Epoch Time','Stream Index', 'Sequence Number', 'Direction', 'pkt_header_values']
df = df[new_cols]

In [62]:
df

,Source IP,Dst IP,Source Port,Dst Port,Epoch Time,Stream Index,Sequence Number,Direction,pkt_header_values
0,192.168.10.50,192.168.10.3,56108,3268,1499428790.315195000,0,1,fwd,"[0.00392156862745098, 0.7803921568627451, 0.77..."
1,192.168.10.50,192.168.10.3,56108,3268,1499428790.315200000,0,1,fwd,"[0.00392156862745098, 0.7803921568627451, 0.77..."
2,192.168.10.50,192.168.10.3,56108,3268,1499428790.315541000,0,404,fwd,"[0.0, 0.20392156862745098, 0.7725490196078432,..."
3,192.168.10.50,192.168.10.3,56108,3268,1499428790.315545000,0,404,fwd,"[0.0, 0.20392156862745098, 0.7725490196078432,..."
4,192.168.10.50,192.168.10.3,42144,389,1499428790.316273000,1,1,fwd,"[0.00392156862745098, 0.7803921568627451, 0.81..."
...,...,...,...,...,...,...,...,...,...
3661382,172.217.12.205,192.168.10.14,443,58093,1499454300.212460000,280715,3982,bwd,"[0.0, 0.9686274509803922, 0.8745098039215686, ..."
3661383,172.217.12.205,192.168.10.14,443,58093,1499454300.212688000,280715,4189,bwd,"[0.00392156862745098, 0.615686274509804, 0.874..."
3661384,172.217.12.205,192.168.10.14,443,58093,1499454300.212736000,280715,4562,bwd,"[0.0, 0.6745098039215687, 0.8745098039215686, ..."
3661385,172.217.12.205,192.168.10.14,443,58093,1499454300.212738000,280715,4694,bwd,"[0.0, 0.33725490196078434, 0.8745098039215686,..."
3661386,93.184.216.172,192.168.10.14,443,58096,1499454300.214231000,280754,5501,bwd,"[0.00392156862745098, 0.16470588235294117, 0.1..."

In [74]:
streams_lst = list(df['Stream Index'].unique())

In [75]:
len(streams_lst)

87847

In [76]:
# 70% of benign data for train, 30% for test benign

In [77]:
random.seed(0)
imlist = random.sample(streams_lst, 61492)

In [78]:
len(imlist)

61492

In [79]:
df_train = df.loc[df['Stream Index'].isin(imlist)]
df_train = df_train.reset_index(inplace = False)

In [80]:
df_test = df.loc[~df['Stream Index'].isin(imlist)]
df_test = df_test.reset_index(inplace = False)

In [93]:
df_test

,index,Source IP,Dst IP,Source Port,Dst Port,Epoch Time,Stream Index,Sequence Number,Direction,pkt_header_values
0,24,192.168.10.9,192.168.10.3,1028,135,1499428835.337052000,2,0,fwd,"[0.0, 0.20392156862745098, 0.0, 0.054901960784..."
1,25,192.168.10.9,192.168.10.3,1028,135,1499428835.337056000,2,0,fwd,"[0.0, 0.20392156862745098, 0.0, 0.054901960784..."
2,26,192.168.10.9,192.168.10.3,1028,135,1499428835.337117000,2,1,fwd,"[0.0, 0.1568627450980392, 0.0, 0.0588235294117..."
3,27,192.168.10.9,192.168.10.3,1028,135,1499428835.337166000,2,1,fwd,"[0.0, 0.1568627450980392, 0.0, 0.0588235294117..."
4,28,192.168.10.9,192.168.10.3,1028,135,1499428835.337745000,2,1,fwd,"[0.0, 0.7843137254901961, 0.0, 0.0627450980392..."
...,...,...,...,...,...,...,...,...,...,...
935485,3661367,157.240.2.25,192.168.10.14,443,58094,1499454300.165864000,280721,3882,bwd,"[0.0, 0.2784313725490196, 0.23529411764705882,..."
935486,3661368,157.240.2.25,192.168.10.14,443,58094,1499454300.165866000,280721,3913,bwd,"[0.0, 0.1568627450980392, 0.23529411764705882,..."
935487,3661373,74.125.22.108,192.168.10.12,465,36806,1499454300.188271000,280714,4091,bwd,"[0.0, 0.20392156862745098, 0.03137254901960784..."
935488,3661379,157.240.2.25,192.168.10.14,443,58094,1499454300.202000000,280721,3914,bwd,"[0.0, 0.1568627450980392, 0.8509803921568627, ..."
935489,3661381,172.217.12.163,192.168.10.14,443,58098,1499454300.211800000,280765,0,bwd,"[0.0, 0.20392156862745098, 0.8431372549019608,..."

In [81]:
streams_lst1 = list(df_test['Stream Index'].unique())

In [95]:
len(streams_lst1)

26355

In [96]:
streams_lst = list(df_test['Stream Index'].unique())
print('Total number of flows in class:', len(streams_lst))    
random.shuffle(streams_lst)

# Directory path where to save the CSV files
directory_path = 'Friday_benign_test_30%_all_data/'

for PKT in range(2, 16):
    
    file_name = f'friday_benign_{PKT}pkt.csv'
    file_path = directory_path + file_name
    

    data = []
    num_pkt = PKT
    pkt_val_pad = [0] * 25


    for j in range(len(streams_lst)):

        df_stream = df_test[df_test['Stream Index'] == streams_lst[j]]


        df_stream = df_stream.sort_values(by = 'Epoch Time')
        df_stream = df_stream.reset_index(drop=True)


        if len(df_stream) >= num_pkt:

            src_node = (int(netaddr.IPAddress(df_stream['Source IP'][0])), int(df_stream['Source Port'][0]))
            dst_node = (int(netaddr.IPAddress(df_stream['Dst IP'][0])), int(df_stream['Dst Port'][0]))
            stream_no = df_stream['Stream Index'][0]

            pkt_val_seq = []

            for k in range(0, num_pkt):

                pkt_val = []
                if df_stream['Direction'][k] == 'fwd':
                    pkt_val = [*df_stream['pkt_header_values'][k], *pkt_val_pad]
                else:
                    pkt_val = [*pkt_val_pad, *df_stream['pkt_header_values'][k]]

                pkt_val_seq.extend(pkt_val)

            data.append([src_node, dst_node, stream_no, pkt_val_seq])

    df1 = pd.DataFrame(data, columns= ['src_node', 'dst_node', 'stream_number', 'pkt_vals'])
    
    df1.to_csv(file_path, index=False)

Total number of flows in class: 26355