In [5]:
import pickle 
import numpy as np
import pandas as pd
import statistics
from PIL import Image
import os 
import random
import time
import matplotlib.pyplot as plt
import netaddr

In [6]:
#pip install netaddr

In [7]:
cwd = os.getcwd()

In [8]:
cwd

'C:\\Users\\Jalal\\Box\\GNN Project\\Code files'

In [9]:
#directory should change based on the device, for laptop it should be users//jalal for office desktop it is users//jghadermazi

In [10]:
wed_data = pd.read_pickle(r'C:\\Users\\Jalal\\Box\\GNN Project\\CICIDS2018\\Bruteforce-4,5\\Wednesday-14-02-2018_Packet_Level_Data_BruteForce.pkl')

In [11]:
df1 = wed_data.copy()

In [12]:
df1[['Payload']] = df1[['Payload']].replace('', '00')

In [13]:
df1

,Epoch Time,Source IP,Dst IP,Source Port,Dst Port,Stream Index,Sequence Number,Eth Header,IP Header,TCP Header,TCP Option,Payload,Direction,Binary Label,Class Label
0,1518611438.595182000,172.31.69.25,131.202.242.193,22,9984,0,1,02ca69c46d0602d8a94e38420800,45100068922a400040064091ac1f451983caf2c1,001627009518ca65936fe7be501800fd681f0000,,e09dde8866a9a4e88956cccc2e2faa1f625b7778480298...,fwd,1.0,4.0
1,1518611438.595250000,172.31.69.25,131.202.242.193,22,9984,0,65,02ca69c46d0602d8a94e38420800,451000e8922b400040064010ac1f451983caf2c1,001627009518caa5936fe7be501800fd689f0000,,241bd2c52a275b8473eb26d44f728f8b57d858fd09b278...,bwd,1.0,4.0
2,1518611438.638559000,131.202.242.193,172.31.69.25,9984,22,0,1,02d8a94e384202ca69c46d060800,4500002828f440006d067d1783caf2c1ac1f4519,27000016936fe7be9518caa5501000fd45100000,,00,fwd,1.0,4.0
3,1518611438.679179000,131.202.242.193,172.31.69.25,9984,22,0,1,02d8a94e384202ca69c46d060800,4500002828f540006d067d1683caf2c1ac1f4519,27000016936fe7be9518cb65501000fc44510000,,00,bwd,1.0,4.0
4,1518611440.798019000,131.202.242.193,172.31.69.25,9984,22,0,1,02d8a94e384202ca69c46d060800,4500006828f640006d067cd583caf2c1ac1f4519,27000016936fe7be9518cb65501800fc66ff0000,,9908e1f4bf086cfa47936090ea9726492ecd1d0beac436...,fwd,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4696840,1518636728.719848000,172.31.69.25,13.58.98.64,22,33852,288092,2667,02ca69c46d0602d8a94e38420800,450000340dc440004006cc4dac1f45190d3a6240,0016843cdbd1e3ccb002b014801000e660d90000,0101080a005fd531bc1f6d79,00,fwd,1.0,5.0
4696841,1518636728.720412000,172.31.69.25,13.58.98.64,22,33856,288094,2314,02ca69c46d0602d8a94e38420800,45000074b489400040062548ac1f45190d3a6240,00168440464c69b183c4f17e801800e661190000,0101080a005fd531bc1f6d78,fff74178818135d3ef145b131ab4f3cd270dd274940195...,bwd,1.0,5.0
4696842,1518636728.720445000,172.31.69.25,13.58.98.64,22,33850,288091,2442,02ca69c46d0602d8a94e38420800,45000074133f40004006c692ac1f45190d3a6240,0016843ad52fd16b09ce9c70801800e661190000,0101080a005fd531bc1f6d78,96a3d0b00caa2a40bdb5f487ea73b250cbf11e1f1f2b88...,fwd,1.0,5.0
4696843,1518636728.720490000,172.31.69.25,13.58.98.64,22,33860,288096,2570,02ca69c46d0602d8a94e38420800,450000941bbf40004006bdf2ac1f45190d3a6240,00168444f2bad9831561cb67801800e661390000,0101080a005fd531bc1f6d79,d4b45a784cca4dfe2674ab36dee64983c216149e96bc92...,bwd,1.0,5.0
4696844,1518636728.720501000,172.31.69.25,13.58.98.64,22,33860,288096,2666,02ca69c46d0602d8a94e38420800,450000341bc040004006be51ac1f45190d3a6240,00168444f2bad9e31561cb67801100e660d90000,0101080a005fd531bc1f6d79,00,fwd,1.0,5.0

In [14]:
#Web attack-Brute Force 1
# Web attack-XSS 2
# Web attack-Sql injection 3
# FTP patator 4
# SSH Patator 5
# DoS GoldenEye 6
# DoS Slowloris 7
# DoS Hulk 8
# DoS Slowhttptest 9
# DDoS 10
# Infiltration 11

In [15]:
df1['Class Label'].value_counts()

5.0    4310125
4.0     386720
Name: Class Label, dtype: int64

In [16]:
df = df1[df1['Class Label']== 5]

In [17]:
df = df.reset_index(inplace = False)

In [18]:
df

,index,Epoch Time,Source IP,Dst IP,Source Port,Dst Port,Stream Index,Sequence Number,Eth Header,IP Header,TCP Header,TCP Option,Payload,Direction,Binary Label,Class Label
0,386720,1518624599.159483000,172.31.69.25,18.221.219.4,21,57454,192744,1,02ca69c46d0602d8a94e38420800,4500002825ef4000400635c7ac1f451912dddb04,0015e06e00000000baf471b150140000c38c0000,,00,fwd,1.0,5.0
1,386721,1518624599.159492000,18.221.219.4,172.31.69.25,57456,21,192745,0,02d8a94e384202ca69c46d060800,4500003cfe2840003f065e7912dddb04ac1f4519,e07000153ad0e37600000000a0026903c92a0000,020405b40402080a9f7598750000000001030307,00,bwd,1.0,5.0
2,386722,1518624599.159493000,172.31.69.25,18.221.219.4,21,57456,192745,1,02ca69c46d0602d8a94e38420800,4500002825f04000400635c6ac1f451912dddb04,0015e070000000003ad0e37750140000d1e80000,,00,fwd,1.0,5.0
3,386723,1518624599.159495000,18.221.219.4,172.31.69.25,57458,21,192746,0,02d8a94e384202ca69c46d060800,4500003cbf1b40003f069d8612dddb04ac1f4519,e07200157702a24500000000a0026903ce270000,020405b40402080a9f7598750000000001030307,00,bwd,1.0,5.0
4,386724,1518624599.159496000,172.31.69.25,18.221.219.4,21,57458,192746,1,02ca69c46d0602d8a94e38420800,4500002825f14000400635c5ac1f451912dddb04,0015e072000000007702a24650140000d6e50000,,00,fwd,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4310120,4696840,1518636728.719848000,172.31.69.25,13.58.98.64,22,33852,288092,2667,02ca69c46d0602d8a94e38420800,450000340dc440004006cc4dac1f45190d3a6240,0016843cdbd1e3ccb002b014801000e660d90000,0101080a005fd531bc1f6d79,00,fwd,1.0,5.0
4310121,4696841,1518636728.720412000,172.31.69.25,13.58.98.64,22,33856,288094,2314,02ca69c46d0602d8a94e38420800,45000074b489400040062548ac1f45190d3a6240,00168440464c69b183c4f17e801800e661190000,0101080a005fd531bc1f6d78,fff74178818135d3ef145b131ab4f3cd270dd274940195...,bwd,1.0,5.0
4310122,4696842,1518636728.720445000,172.31.69.25,13.58.98.64,22,33850,288091,2442,02ca69c46d0602d8a94e38420800,45000074133f40004006c692ac1f45190d3a6240,0016843ad52fd16b09ce9c70801800e661190000,0101080a005fd531bc1f6d78,96a3d0b00caa2a40bdb5f487ea73b250cbf11e1f1f2b88...,fwd,1.0,5.0
4310123,4696843,1518636728.720490000,172.31.69.25,13.58.98.64,22,33860,288096,2570,02ca69c46d0602d8a94e38420800,450000941bbf40004006bdf2ac1f45190d3a6240,00168444f2bad9831561cb67801800e661390000,0101080a005fd531bc1f6d79,d4b45a784cca4dfe2674ab36dee64983c216149e96bc92...,bwd,1.0,5.0
4310124,4696844,1518636728.720501000,172.31.69.25,13.58.98.64,22,33860,288096,2666,02ca69c46d0602d8a94e38420800,450000341bc040004006be51ac1f45190d3a6240,00168444f2bad9e31561cb67801100e660d90000,0101080a005fd531bc1f6d79,00,fwd,1.0,5.0

In [19]:
ip_header_lst = []

for i in range(len(df)):
    x = df['IP Header'][i]
    byte_array = bytes.fromhex(x)
    byte_lst = list(byte_array)
    if (len(byte_lst) < 20):
            output = np.pad(byte_lst, (0, 20-len(byte_lst)), 'constant')
    else:
            output = np.array(byte_lst[0:20].copy())
            
    output = np.delete(output, [0, 1, 9, 12, 13, 14, 15, 16, 17, 18, 19])
    
    output = np.abs(output.astype(float))/255
    ip_header_lst.append(output)
    
df['IP Header Array'] = ip_header_lst

In [20]:
tcp_header_lst = []

for i in range(len(df)):
    x = df['TCP Header'][i]
    byte_array = bytes.fromhex(x)
    byte_lst = list(byte_array)
    if (len(byte_lst) < 20):
            output = np.pad(byte_lst, (0, 20-len(byte_lst)), 'constant')
    else:
            output = np.array(byte_lst[0:20].copy())
            
    output = np.delete(output, [0, 1, 2, 3])
    output = np.abs(output.astype(float))/255
    
    tcp_header_lst.append(output)
    
df['TCP Header Array'] = tcp_header_lst

In [21]:
df['pkt_header_values'] = df.apply(lambda x : (np.append(x['IP Header Array'], x['TCP Header Array'])), axis=1)

In [22]:
new_cols = ['Source IP', 'Dst IP', 'Source Port', 'Dst Port','Epoch Time','Stream Index', 'Sequence Number', 'Direction', 'pkt_header_values']
df = df[new_cols]

In [23]:
df

,Source IP,Dst IP,Source Port,Dst Port,Epoch Time,Stream Index,Sequence Number,Direction,pkt_header_values
0,172.31.69.25,18.221.219.4,21,57454,1518624599.159483000,192744,1,fwd,"[0.0, 0.1568627450980392, 0.1450980392156863, ..."
1,18.221.219.4,172.31.69.25,57456,21,1518624599.159492000,192745,0,bwd,"[0.0, 0.23529411764705882, 0.996078431372549, ..."
2,172.31.69.25,18.221.219.4,21,57456,1518624599.159493000,192745,1,fwd,"[0.0, 0.1568627450980392, 0.1450980392156863, ..."
3,18.221.219.4,172.31.69.25,57458,21,1518624599.159495000,192746,0,bwd,"[0.0, 0.23529411764705882, 0.7490196078431373,..."
4,172.31.69.25,18.221.219.4,21,57458,1518624599.159496000,192746,1,fwd,"[0.0, 0.1568627450980392, 0.1450980392156863, ..."
...,...,...,...,...,...,...,...,...,...
4310120,172.31.69.25,13.58.98.64,22,33852,1518636728.719848000,288092,2667,fwd,"[0.0, 0.20392156862745098, 0.05098039215686274..."
4310121,172.31.69.25,13.58.98.64,22,33856,1518636728.720412000,288094,2314,bwd,"[0.0, 0.4549019607843137, 0.7058823529411765, ..."
4310122,172.31.69.25,13.58.98.64,22,33850,1518636728.720445000,288091,2442,fwd,"[0.0, 0.4549019607843137, 0.07450980392156863,..."
4310123,172.31.69.25,13.58.98.64,22,33860,1518636728.720490000,288096,2570,bwd,"[0.0, 0.5803921568627451, 0.10588235294117647,..."
4310124,172.31.69.25,13.58.98.64,22,33860,1518636728.720501000,288096,2666,fwd,"[0.0, 0.20392156862745098, 0.10588235294117647..."

In [24]:
# 70% of benign data for train, 30% for test benign

In [25]:
streams_lst = list(df['Stream Index'].unique())
streams_lst = streams_lst[0:2000]
print('Total number of flows in class:', len(streams_lst))    
random.shuffle(streams_lst)

# Directory path where to save the CSV files
directory_path = '2018_ssh_patator/'

for PKT in range(2, 16):
    
    file_name = f'2018_ssh_patator_{PKT}pkt.csv'
    file_path = directory_path + file_name
    

    data = []
    num_pkt = PKT
    pkt_val_pad = [0] * 25


    for j in range(len(streams_lst)):

        df_stream = df[df['Stream Index'] == streams_lst[j]]


        df_stream = df_stream.sort_values(by = 'Epoch Time')
        df_stream = df_stream.reset_index(drop=True)


        if len(df_stream) >= num_pkt:

            src_node = (int(netaddr.IPAddress(df_stream['Source IP'][0])), int(df_stream['Source Port'][0]))
            dst_node = (int(netaddr.IPAddress(df_stream['Dst IP'][0])), int(df_stream['Dst Port'][0]))
            stream_no = df_stream['Stream Index'][0]

            pkt_val_seq = []

            for k in range(0, num_pkt):

                pkt_val = []
                if df_stream['Direction'][k] == 'fwd':
                    pkt_val = [*df_stream['pkt_header_values'][k], *pkt_val_pad]
                else:
                    pkt_val = [*pkt_val_pad, *df_stream['pkt_header_values'][k]]

                pkt_val_seq.extend(pkt_val)

            data.append([src_node, dst_node, stream_no, pkt_val_seq])

    df1 = pd.DataFrame(data, columns= ['src_node', 'dst_node', 'stream_number', 'pkt_vals'])
    
    df1.to_csv(file_path, index=False)

Total number of flows in class: 2000